const FABRIC_RENDER = {
  STROKE_WIDTH: 2,
  STROKE_COLOR: "black",
  TEXT_PADDING: 40,
  TEXT_WEIGHT: 500,
  TEXT_SIZE: 20,
  TEXT_FAMILY: "Noto Sans KR",
  TEXT_LINE_HEIGHT: 1.2,
  TEXTBOX_WIDTH: 550,
  TEXTBOX_OPACITY: 0.8,
  TEXT_BACKGROUND_COLOR: "rgba(0, 0, 0, 0.8)",
  TEXT_COLOR: "rgba(255, 255, 255, 1)",
};

export default FABRIC_RENDER;
